#!/usr/bin/env node
// Generates Tailwind v4 @theme CSS from Figma's native variable export
// format (W3C DTCG design tokens + a `com.figma.*` $extensions block).
// See docs/decisions/0008-figma-token-import-pipeline.md for the
// pipeline this implements.
//
// Usage:
//   node scripts/build-tokens.mjs
//
// Drop exported .json files into tokens-source/. Files that are
// different Figma *modes* of the same variable collection (e.g.
// scale-large.tokens.json + scale-medium.tokens.json) are detected via
// each file's own `$extensions.com.figma.modeName` and merged into one
// collection with mode-scoped CSS overrides.
//
// Figma's exporter bakes every alias's resolved literal directly into
// `$value`, and separately records the source relationship in
// `$extensions.com.figma.aliasData` (targetVariableName/
// targetVariableSetName). This script prefers that relationship over
// the baked literal — an aliased token is emitted as `var(--target)`,
// not a copy of the value — so the primitive -> semantic -> component
// chain (see docs/glossary.yaml's "token layer order" entry) stays real
// CSS variable indirection, not flattened duplicates.
//
// This script only supports what tokens-source/ has actually contained
// so far: numbers, strings, DTCG `color` values, and aliases carried
// via `com.figma.aliasData`. It fails loudly (rather than guessing) on
// shapes it doesn't handle yet.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, basename, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const PACKAGE_ROOT = fileURLToPath(new URL('..', import.meta.url));
const SOURCE_DIR = join(PACKAGE_ROOT, 'tokens-source');
const OUTPUT_PATH = join(PACKAGE_ROOT, 'src', 'tokens', 'generated.css');

// Top-level token group name -> Tailwind @theme namespace it maps to.
// Extend this when a new top-level group shows up in tokens-source/.
const NAMESPACES = {
  space: 'spacing',
};

// Unit appended to bare numeric values, keyed by the CSS namespace
// (not the source group name) — Figma exports FLOAT variables as
// unitless numbers, so the pipeline has to know which namespaces are
// pixel dimensions.
const UNITS = {
  spacing: 'px',
};

// Some collections group tokens under a name that doesn't say what
// they are (primitives-light/dark's top-level group is a palette name
// like "seagull", not "color"). This prefixes every token path in that
// collection before namespace resolution, so `seagull.300` becomes
// `color.seagull.300` -> `--color-seagull-300`. Collections whose own
// group names are already descriptive (semantics' `bg.fill.primary`,
// components' `button.primary.background`) need no entry here.
const COLLECTION_PREFIX = {
  primitives: 'color',
};

// Collections with more than one Figma mode MUST declare their default
// (unscoped) mode here — see docs/decisions/0007 for why `scale`
// defaults to `medium`, and docs/decisions/0008 for why `primitives`
// defaults to `light`. Add an entry whenever a new multi-mode
// collection lands in tokens-source/.
const DEFAULT_MODE = {
  scale: 'medium',
  primitives: 'light',
};

const GENERATED_HEADER = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
 * Source: tokens-source/*.json (Figma variable export)
 * Regenerate: npm run tokens:build
 */
`;

// Cosmetic only — CSS custom properties resolve var() references at
// used-value time, not declaration order, so this doesn't affect
// correctness. Ordered to read primitive -> semantic -> component (see
// docs/glossary.yaml's "token layer order" entry), with unrelated axes
// (scale) last. Anything not listed here is appended after, in the
// order it was first encountered in tokens-source/.
const COLLECTION_ORDER = ['primitives', 'semantics', 'components', 'scale'];

function isLeaf(node) {
  return node && typeof node === 'object' && '$value' in node;
}

function walk(node, path, out) {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    const nextPath = [...path, key];
    if (isLeaf(child)) {
      out.set(nextPath.join('.'), {
        type: child.$type,
        value: child.$value,
        aliasData: child.$extensions?.['com.figma.aliasData'] ?? null,
      });
    } else if (child && typeof child === 'object') {
      walk(child, nextPath, out);
    }
  }
  return out;
}

function loadFile(file) {
  const json = JSON.parse(readFileSync(file, 'utf8'));
  const modeName = json.$extensions?.['com.figma.modeName'] ?? null;
  return { tokens: walk(json, [], new Map()), modeName };
}

// scale-large.tokens.json -> collection "scale", mode "large" — the
// mode comes from the file's own $extensions.com.figma.modeName, the
// filename suffix is just expected to agree with it, never trusted on
// its own.
function collectionNameFor(fileBase, modeName) {
  if (modeName && fileBase.endsWith(`-${modeName}`)) {
    return fileBase.slice(0, -(modeName.length + 1));
  }
  return fileBase;
}

function applyCollectionPrefix(tokens, collectionName) {
  const prefix = COLLECTION_PREFIX[collectionName];
  if (!prefix) return tokens;
  const prefixed = new Map();
  for (const [path, entry] of tokens) {
    prefixed.set(`${prefix}.${path}`, entry);
  }
  return prefixed;
}

function loadCollections() {
  const files = readdirSync(SOURCE_DIR).filter((f) => f.endsWith('.json'));
  if (files.length === 0) {
    throw new Error(`No .json files found in ${relative(PACKAGE_ROOT, SOURCE_DIR)}/`);
  }

  const collections = new Map(); // collectionName -> Map<modeKey, tokenMap>
  for (const file of files) {
    const fileBase = basename(file).replace(/\.tokens\.json$|\.json$/, '');
    const { tokens, modeName } = loadFile(join(SOURCE_DIR, file));
    const collectionName = collectionNameFor(fileBase, modeName);
    const modeKey = modeName ?? '__default__';

    if (!collections.has(collectionName)) collections.set(collectionName, new Map());
    const modes = collections.get(collectionName);
    if (modes.has(modeKey)) {
      throw new Error(
        `Collection "${collectionName}" has two files claiming mode "${modeKey}" — check tokens-source/${file}`
      );
    }
    modes.set(modeKey, applyCollectionPrefix(tokens, collectionName));
  }
  return collections;
}

function orderedCollections(collections) {
  const known = COLLECTION_ORDER.filter((name) => collections.has(name));
  const rest = [...collections.keys()].filter((name) => !COLLECTION_ORDER.includes(name));
  return [...known, ...rest].map((name) => [name, collections.get(name)]);
}

function cssVarName(path) {
  const [group, ...rest] = path.split('.');
  const namespace = NAMESPACES[group] ?? group;
  return { namespace, varName: `--${namespace}-${rest.join('-')}` };
}

// Every var name any collection/mode will emit, used to catch an alias
// pointing at a token that doesn't exist (renamed/missing source).
function buildVarRegistry(collections) {
  const registry = new Set();
  for (const modes of collections.values()) {
    for (const tokens of modes.values()) {
      for (const path of tokens.keys()) {
        registry.add(cssVarName(path).varName);
      }
    }
  }
  return registry;
}

function aliasTargetVarName(aliasData) {
  const rawPath = aliasData.targetVariableName.split('/').join('.');
  const prefix = COLLECTION_PREFIX[aliasData.targetVariableSetName];
  const fullPath = prefix ? `${prefix}.${rawPath}` : rawPath;
  return cssVarName(fullPath).varName;
}

function formatColor(value, path) {
  if (typeof value !== 'object' || value === null || !Array.isArray(value.components)) {
    throw new Error(`Token "${path}" has a $type "color" value that isn't shaped as expected: ${JSON.stringify(value)}`);
  }
  if (value.alpha === 1 && typeof value.hex === 'string') {
    return value.hex;
  }
  const [r, g, b] = value.components.map((c) => Math.round(c * 255));
  return `rgba(${r}, ${g}, ${b}, ${value.alpha})`;
}

function formatValue(entry, namespace, path) {
  const { value, type } = entry;
  if (typeof value === 'string' && /^\{.*\}$/.test(value)) {
    throw new Error(
      `Token "${path}" is a DTCG alias string ("${value}") — this pipeline only resolves aliases via ` +
        `$extensions.com.figma.aliasData, not the {a.b.c} syntax. Extend build-tokens.mjs if this shape shows up.`
    );
  }
  if (type === 'color') {
    return formatColor(value, path);
  }
  if (typeof value === 'number') {
    return `${value}${UNITS[namespace] ?? ''}`;
  }
  if (typeof value === 'string') {
    return value;
  }
  throw new Error(
    `Token "${path}" has an unsupported $type "${type}" (value: ${JSON.stringify(value)}). ` +
      `Extend build-tokens.mjs's formatValue() to handle it.`
  );
}

function emitTokenLines(tokens, registry) {
  const lines = [];
  for (const [path, entry] of tokens) {
    const { namespace, varName } = cssVarName(path);
    let cssValue;
    if (entry.aliasData) {
      const targetVarName = aliasTargetVarName(entry.aliasData);
      if (!registry.has(targetVarName)) {
        throw new Error(
          `Token "${path}" aliases "${entry.aliasData.targetVariableName}" in collection ` +
            `"${entry.aliasData.targetVariableSetName}", which resolves to unknown var "${targetVarName}" — ` +
            `check tokens-source/ for a missing or renamed source token.`
        );
      }
      cssValue = `var(${targetVarName})`;
    } else {
      cssValue = formatValue(entry, namespace, path);
    }
    lines.push(`  ${varName}: ${cssValue};`);
  }
  return lines;
}

function generateCss(collections) {
  const registry = buildVarRegistry(collections);
  const themeLines = [];
  const overrideBlocks = [];

  for (const [collectionName, modes] of orderedCollections(collections)) {
    const modeKeys = [...modes.keys()];

    if (modeKeys.length === 1) {
      themeLines.push(...emitTokenLines(modes.get(modeKeys[0]), registry));
      continue;
    }

    const defaultMode = DEFAULT_MODE[collectionName];
    if (!defaultMode || !modes.has(defaultMode)) {
      throw new Error(
        `Collection "${collectionName}" has multiple modes (${modeKeys.join(', ')}) but no default ` +
          `configured. Add DEFAULT_MODE["${collectionName}"] in build-tokens.mjs.`
      );
    }

    themeLines.push(...emitTokenLines(modes.get(defaultMode), registry));

    for (const modeKey of modeKeys) {
      if (modeKey === defaultMode) continue;
      overrideBlocks.push({
        selector: `[data-${collectionName}="${modeKey}"]`,
        lines: emitTokenLines(modes.get(modeKey), registry),
      });
    }
  }

  const parts = [GENERATED_HEADER, '@theme {', ...themeLines, '}'];
  for (const block of overrideBlocks) {
    parts.push('', `${block.selector} {`, ...block.lines, '}');
  }
  return parts.join('\n') + '\n';
}

function main() {
  const collections = loadCollections();
  const css = generateCss(collections);
  writeFileSync(OUTPUT_PATH, css, 'utf8');
  console.log(`tokens:build wrote ${relative(PACKAGE_ROOT, OUTPUT_PATH)}`);
}

try {
  main();
} catch (err) {
  console.error(`tokens:build failed: ${err.message}`);
  process.exitCode = 1;
}
